// AUTO-GENERATED by scripts/sync-fallback-catalog.mjs from
//   https://api.bridgekitty.persistence.one/api/v1/catalog
// Generated at 2026-05-11T08:31:14.537Z.
// Do NOT edit by hand — run `npm run sync:fallback` after backend
// catalog changes (bridgekitty-backend's prisma/data/catalog.ts).
import type { Chain, Token } from './catalog';

/**
 * Minimal hardcoded catalog snapshot used only when:
 *   1. There is no cached snapshot in localStorage (first-ever visit), AND
 *   2. The fetch of /api/v1/catalog fails or times out.
 *
 * Mirrors what /api/v1/catalog returned at sync time. Updating this file
 * by hand will pass typecheck but get clobbered the next time anyone runs
 * `npm run sync:fallback`. Edit the upstream catalog instead:
 * bridgekitty-backend/prisma/data/catalog.ts.
 */
export const FALLBACK_CATALOG: { chains: Chain[]; tokensByChainKey: Record<string, Token[]> } = {
  chains: [
    {
      "key": "ethereum",
      "chainId": 1,
      "name": "Ethereum",
      "logoURI": "/chains/ethereum.svg",
      "blockExplorerUrl": "https://etherscan.io/tx/"
    },
    {
      "key": "base",
      "chainId": 8453,
      "name": "Base",
      "logoURI": "/chains/base.svg",
      "blockExplorerUrl": "https://basescan.org/tx/"
    },
    {
      "key": "bob",
      "chainId": 60808,
      "name": "BOB",
      "logoURI": "/chains/bob.png",
      "blockExplorerUrl": "https://explorer.gobob.xyz/tx/"
    },
    {
      "key": "bsc",
      "chainId": 56,
      "name": "BNB Chain",
      "logoURI": "/chains/bnb.svg",
      "blockExplorerUrl": "https://bscscan.com/tx/"
    },
    {
      "key": "monad",
      "chainId": 143,
      "name": "Monad",
      "logoURI": "/chains/monad.png",
      "blockExplorerUrl": "https://monadscan.com/tx/"
    },
    {
      "key": "polygon",
      "chainId": 137,
      "name": "Polygon",
      "logoURI": "/chains/polygon.svg",
      "blockExplorerUrl": "https://polygonscan.com/tx/"
    },
    {
      "key": "bitlayer",
      "chainId": 200901,
      "name": "Bitlayer",
      "logoURI": "/chains/bitlayer.png",
      "blockExplorerUrl": "https://www.btrscan.com/tx/"
    },
    {
      "key": "b2-network",
      "chainId": 223,
      "name": "B² Network",
      "logoURI": "/chains/b2-network.png",
      "blockExplorerUrl": "https://explorer.bsquared.network/tx/"
    },
    {
      "key": "rootstock",
      "chainId": 30,
      "name": "Rootstock",
      "logoURI": "/chains/rootstock.png",
      "blockExplorerUrl": "https://rootstock.blockscout.com/tx/"
    },
    {
      "key": "core",
      "chainId": 1116,
      "name": "Core",
      "logoURI": "/chains/core.png",
      "blockExplorerUrl": "https://scan.coredao.org/tx/"
    },
    {
      "key": "merlin",
      "chainId": 4200,
      "name": "Merlin",
      "logoURI": "/chains/merlin.jpeg",
      "blockExplorerUrl": "https://scan.merlinchain.io/tx/"
    }
  ],
  tokensByChainKey: {
    "ethereum": [
      {
        "symbol": "ETH",
        "name": "Ether",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/eth.svg",
        "tags": [
          "native"
        ]
      },
      {
        "symbol": "WBTC",
        "name": "Wrapped Bitcoin",
        "address": "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
        "decimals": 8,
        "logoURI": "/token-icons/wbtc.png",
        "tags": [
          "btc-variant"
        ]
      },
      {
        "symbol": "cbBTC",
        "name": "Coinbase Wrapped BTC",
        "address": "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf",
        "decimals": 8,
        "logoURI": "/token-icons/cbbtc.png",
        "tags": [
          "btc-variant"
        ]
      },
      {
        "symbol": "USDC",
        "name": "USD Coin",
        "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "decimals": 6,
        "logoURI": "/token-icons/usdc.svg",
        "tags": [
          "stablecoin"
        ]
      },
      {
        "symbol": "USDT",
        "name": "Tether USD",
        "address": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
        "decimals": 6,
        "logoURI": "/token-icons/usdt.svg",
        "tags": [
          "stablecoin"
        ]
      },
      {
        "symbol": "DAI",
        "name": "Dai Stablecoin",
        "address": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
        "decimals": 18,
        "logoURI": "/token-icons/dai.svg",
        "tags": [
          "stablecoin"
        ]
      }
    ],
    "base": [
      {
        "symbol": "ETH",
        "name": "Ether",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/eth.svg",
        "tags": [
          "native"
        ]
      },
      {
        "symbol": "cbBTC",
        "name": "Coinbase Wrapped BTC",
        "address": "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf",
        "decimals": 8,
        "logoURI": "/token-icons/cbbtc.png",
        "tags": [
          "btc-variant"
        ]
      },
      {
        "symbol": "WBTC",
        "name": "Wrapped Bitcoin",
        "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c",
        "decimals": 8,
        "logoURI": "/token-icons/wbtc.png",
        "tags": [
          "btc-variant"
        ]
      },
      {
        "symbol": "USDC",
        "name": "USD Coin",
        "address": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
        "decimals": 6,
        "logoURI": "/token-icons/usdc.svg",
        "tags": [
          "stablecoin"
        ]
      },
      {
        "symbol": "USDT",
        "name": "Tether USD",
        "address": "0xfde4C96c8593536e31F229EA8f37b2Ada2699bb2",
        "decimals": 6,
        "logoURI": "/token-icons/usdt.svg",
        "tags": [
          "stablecoin"
        ]
      },
      {
        "symbol": "DAI",
        "name": "Dai Stablecoin",
        "address": "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb",
        "decimals": 18,
        "logoURI": "/token-icons/dai.svg",
        "tags": [
          "stablecoin"
        ]
      }
    ],
    "bob": [
      {
        "symbol": "ETH",
        "name": "Ether",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/eth.svg",
        "tags": [
          "native"
        ]
      },
      {
        "symbol": "UNIBTC",
        "name": "uniBTC",
        "address": "0x236f8c0a61da474db21b693fb2ea7aab0c803894",
        "decimals": 8,
        "logoURI": "/token-icons/unibtc.png",
        "tags": [
          "btc-variant"
        ]
      },
      {
        "symbol": "WBTC",
        "name": "Wrapped BTC",
        "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c",
        "decimals": 8,
        "logoURI": "/token-icons/wbtc.png",
        "tags": [
          "btc-variant"
        ]
      }
    ],
    "bsc": [
      {
        "symbol": "BNB",
        "name": "BNB",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/bnb.svg",
        "tags": [
          "native"
        ]
      },
      {
        "symbol": "WBTC",
        "name": "Wrapped Bitcoin",
        "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c",
        "decimals": 8,
        "logoURI": "/token-icons/wbtc.png",
        "tags": [
          "btc-variant"
        ]
      },
      {
        "symbol": "BTCB",
        "name": "Binance-Peg BTCB Token",
        "address": "0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c",
        "decimals": 18,
        "logoURI": "/token-icons/btcb.png",
        "tags": [
          "btc-variant"
        ]
      },
      {
        "symbol": "USDC",
        "name": "USD Coin",
        "address": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
        "decimals": 18,
        "logoURI": "/token-icons/usdc.svg",
        "tags": [
          "stablecoin"
        ]
      },
      {
        "symbol": "USDT",
        "name": "Tether USD",
        "address": "0x55d398326f99059fF775485246999027B3197955",
        "decimals": 18,
        "logoURI": "/token-icons/usdt.svg",
        "tags": [
          "stablecoin"
        ]
      }
    ],
    "monad": [
      {
        "symbol": "MON",
        "name": "Monad",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/mon.png",
        "tags": [
          "native"
        ]
      },
      {
        "symbol": "WBTC",
        "name": "Wrapped Bitcoin",
        "address": "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c",
        "decimals": 8,
        "logoURI": "/token-icons/wbtc.png",
        "tags": [
          "btc-variant"
        ]
      }
    ],
    "polygon": [
      {
        "symbol": "POL",
        "name": "POL",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/matic.svg",
        "tags": [
          "native"
        ]
      },
      {
        "symbol": "WBTC",
        "name": "Wrapped Bitcoin",
        "address": "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6",
        "decimals": 8,
        "logoURI": "/token-icons/wbtc.png",
        "tags": [
          "btc-variant"
        ]
      },
      {
        "symbol": "USDC",
        "name": "USD Coin",
        "address": "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359",
        "decimals": 6,
        "logoURI": "/token-icons/usdc.svg",
        "tags": [
          "stablecoin"
        ]
      },
      {
        "symbol": "USDT",
        "name": "Tether USD",
        "address": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
        "decimals": 6,
        "logoURI": "/token-icons/usdt.svg",
        "tags": [
          "stablecoin"
        ]
      }
    ],
    "bitlayer": [
      {
        "symbol": "BTC",
        "name": "Bitcoin",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/btc.png",
        "tags": [
          "native",
          "btc-variant"
        ]
      }
    ],
    "b2-network": [
      {
        "symbol": "BTC",
        "name": "Bitcoin",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/btc.png",
        "tags": [
          "native",
          "btc-variant"
        ]
      },
      {
        "symbol": "WBTC",
        "name": "Wrapped BTC",
        "address": "0x4200000000000000000000000000000000000006",
        "decimals": 8,
        "logoURI": "/token-icons/wbtc.png",
        "tags": [
          "btc-variant"
        ]
      }
    ],
    "rootstock": [
      {
        "symbol": "RBTC",
        "name": "Rootstock Bitcoin",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/rbtc.png",
        "tags": [
          "native",
          "btc-variant"
        ]
      },
      {
        "symbol": "WRBTC",
        "name": "Wrapped RBTC",
        "address": "0x542fda317318ebf1d3deaf76e0b632741a7e677d",
        "decimals": 18,
        "logoURI": "/token-icons/rbtc.png",
        "tags": [
          "btc-variant"
        ]
      }
    ],
    "core": [
      {
        "symbol": "CORE",
        "name": "Core",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/core.png",
        "tags": [
          "native"
        ]
      }
    ],
    "merlin": [
      {
        "symbol": "MERL",
        "name": "Merlin",
        "address": "0x5c46bff4b38dc1eae09c5bac65872a1d8bc87378",
        "decimals": 18,
        "logoURI": "/token-icons/merl.png",
        "tags": []
      },
      {
        "symbol": "WBTC",
        "name": "Wrapped BTC",
        "address": "0xf6d226f9dc15d9bb51182815b320d3fbe324e1ba",
        "decimals": 8,
        "logoURI": "/token-icons/wbtc.png",
        "tags": [
          "btc-variant"
        ]
      },
      {
        "symbol": "BTC",
        "name": "Bitcoin",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "decimals": 18,
        "logoURI": "/token-icons/btc.png",
        "tags": [
          "native",
          "btc-variant"
        ]
      }
    ]
  },
};
